name: sync GitHub to GitLab

on:
  push:
    branches:
      - '*'  # 适用于所有分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout GitHub repository
        uses: actions/checkout@v3

      - name: set up GitLab repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}  # 从 Secrets 获取 GitLab Token
        run: |
          GITLAB_GROUP="${{ github.repository_owner }}"
          GITLAB_REPO="${{ github.event.repository.name }}"
          
          echo "GitLab Group=${GITLAB_GROUP}"
          echo "GitLab Repository=${GITLAB_REPO}"
          echo "GitLab Token=${GITLAB_TOKEN}"
          
          # 获取当前 GitHub 分支名
          GITHUB_BRANCH=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')

          # 设置 GitLab 仓库的远程 URL
          GITLAB_URL="https://oauth2:${GITLAB_TOKEN}@gitlab.com/${GITLAB_GROUP}/${GITLAB_REPO}.git"

          # 添加 GitLab 作为新的 remote
          git remote add gitlab $GITLAB_URL

          # 确保仓库是完整克隆
          git fetch --unshallow

          # 推送当前分支到 GitLab
          git push --set-upstream gitlab $GITHUB_BRANCH  # 将当前分支推送到 GitLab 仓库

      - name: Verify GitLab Push
        run: |
          git remote -v  # 显示 GitLab 仓库信息
