name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}  # 从 Secrets 读取 Token
          GITLAB_GROUP: ${{ vars.GITLAB_GROUP }}      # 从 Variables 读取 Group 名称
          GITLAB_REPO: ${{ vars.GITLAB_REPO }}        # 从 Variables 读取 Repo 名称
        run: |
          GITLAB_URL="https://oauth2:${GITLAB_TOKEN}@gitlab.com/${GITLAB_GROUP}/${GITLAB_REPO}.git"
          
          # 设置 GitLab remote（如果已存在则更新）
          git remote add gitlab $GITLAB_URL || git remote set-url gitlab $GITLAB_URL
          
          # 获取 GitLab 最新的 main 分支
          git fetch gitlab main
          
          # 确保与远程同步，避免冲突
          git reset --hard origin/main
          git merge --ff-only gitlab/main || git rebase gitlab/main || echo "No need to merge"

          # 推送最新变更到 GitLab
          git push gitlab main
