name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          GITLAB_URL="https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ vars.GITLAB_GROUP }}/${{ vars.GITLAB_REPO }}.git"
          git remote add gitlab $GITLAB_URL
          git fetch gitlab main git merge --no-edit gitlab/main || git rebase gitlab/main
          git push gitlab main
